# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    agreement_signature_certificate_path: '%env(string:AGREEMENT_SIGNATURE_CERTIFICATE_PATH)%'
    agreement_signature_private_key_path: '%env(string:AGREEMENT_SIGNATURE_PRIVATE_KEY_PATH)%'
    agreement_signature_private_key_passphrase: '%env(string:AGREEMENT_SIGNATURE_PRIVATE_KEY_PASSPHRASE)%'
    wp_bridge_key: '%env(string:WP_BRIDGE_KEY)%'
    wp_bridge_secret: '%env(string:WP_BRIDGE_SECRET)%'
    contracts_storage_path: '%kernel.project_dir%/shared/agreements'
    agreements_storage_path: '%kernel.project_dir%/var/agreements'
    enable_signatures: '%env(bool:ENABLE_SIGNATURES)%'
    signature_api_base_url: '%env(default::SIGNATURE_API_BASE_URL)%'
    signature_api_token: '%env(default::SIGNATURE_API_TOKEN)%'
    audit_storage_path: '%kernel.project_dir%/shared/audit'
    signature_validation_api_url: '%env(default::SIGNATURE_API_URL)%'
    signature_ttl_days: '%env(int:SIGNATURE_TTL_DAYS)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'

    Stripe\StripeClient:
        arguments:
            $config:
                api_key: '%env(STRIPE_SECRET_KEY)%'

    App\Service\AvailabilityService:
        arguments:
            $appointmentRepository: '@App\Repository\AppointmentRepository'

    App\Service\AppointmentService:
        arguments:
            $em: '@doctrine.orm.entity_manager'
            $invoiceService: '@App\Service\InvoiceService'

    App\Service\AgreementService:
        arguments:
            $signatureCertificatePath: '%agreement_signature_certificate_path%'
            $signaturePrivateKeyPath: '%agreement_signature_private_key_path%'
            $signaturePrivateKeyPassphrase: '%agreement_signature_private_key_passphrase%'

    App\Service\ContractGenerator:
        arguments:
            $contractsStoragePath: '%contracts_storage_path%'

    App\Service\AuditLogger:
        arguments:
            $auditStoragePath: '%audit_storage_path%'

    App\Service\SignatureValidator:
        arguments:
            $validationApiUrl: '%signature_validation_api_url%'
            $signatureTtlDays: '%signature_ttl_days%'

    App\Service\Logging\AnonymizeIpProcessor:
        tags:
            - { name: monolog.processor, handler: main }

    App\Service\SignatureClient:
        arguments:
            $contractsStoragePath: '%contracts_storage_path%'
            $signaturesEnabled: '%enable_signatures%'
            $signatureBaseUrl: '%signature_api_base_url%'
            $signatureToken: '%signature_api_token%'

    App\Service\HealthCheckService:
        arguments:
            $agreementsStoragePath: '%agreements_storage_path%'
            $auditStoragePath: '%audit_storage_path%'

    App\Controller\Api\WpContractController:
        arguments:
            $wpBridgeSecret: '%wp_bridge_secret%'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    App\Service\ReminderService:
        arguments:
            $whatsappDsn: '%env(WHATSAPP_DSN)%'
            $smsDsn: '%env(SMS_DSN)%'

    App\RanchBooking\EventSubscriber\HmacRequestSubscriber:
        arguments:
            $wpBridgeKey: '%wp_bridge_key%'
            $wpBridgeSecret: '%wp_bridge_secret%'
