version: '3.9'

services:
  db:
    image: postgres:15
    env_file: .env
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U $${POSTGRES_USER:-postgres} -d $${POSTGRES_DB:-postgres}
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  wp-db:
    image: mariadb:11
    env_file: .env
    volumes:
      - wp-db-data:/var/lib/mysql
    restart: unless-stopped
    healthcheck:
      test:
        - CMD-SHELL
        - |
          MYSQL_PWD="$${MARIADB_PASSWORD:-$${MARIADB_ROOT_PASSWORD:-}}"
          export MYSQL_PWD
          mysqladmin ping -h localhost -u "$${MARIADB_USER:-root}" --silent
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  backend:
    image: silentoakranch/backend:latest
    build: ./backend
    env_file: .env
    restart: unless-stopped
    depends_on:
      - db
    expose:
      - "8080"
    environment:
      VIRTUAL_PATH: "/api"
      VIRTUAL_PORT: "8080"
    volumes:
      - ./shared/jwt/backend:/var/www/backend/config/jwt
      - ./shared/backend/var:/var/www/backend/var
      - ./shared/agreements/signing:/var/www/backend/config/agreements
    networks:
      - default
      - symfony-wp
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

  frontend:
    image: silentoakranch/frontend:latest
    build:
      context: ./frontend
      args:
        VITE_STRIPE_PUBLISHABLE_KEY: ${VITE_STRIPE_PUBLISHABLE_KEY}
    expose:
      - "80"
    environment:
      VIRTUAL_HOST: "${DOMAIN}"
      VIRTUAL_PORT: "80"
      LETSENCRYPT_HOST: "${DOMAIN}"
      LETSENCRYPT_EMAIL: "${LETSENCRYPT_EMAIL}"
    healthcheck:
      test:
        - CMD-SHELL
        - status=0; wget -q --spider http://127.0.0.1/ >/dev/null 2>&1 || status=$$?; [ $$status -eq 0 ] || [ $$status -eq 8 ]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 20s

  wordpress:
    image: php:8.3-apache
    env_file: .env
    depends_on:
      - wp-db
    volumes:
      - wp-content:/var/www/html/wp-content
    environment:
      VIRTUAL_HOST: "book.silentoakranch.de"
      LETSENCRYPT_HOST: "book.silentoakranch.de"
    networks:
      - default
      - symfony-wp

  proxy:
    image: nginxproxy/nginx-proxy:latest
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - proxy-certs:/etc/nginx/certs:rw
      - proxy-vhost:/etc/nginx/vhost.d
      - proxy-html:/usr/share/nginx/html
    healthcheck:
      test:
        - CMD-SHELL
        - status=0; wget -q --spider http://127.0.0.1/ >/dev/null 2>&1 || status=$$?; [ $$status -eq 0 ] || [ $$status -eq 8 ]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 20s

  letsencrypt:
    image: nginxproxy/acme-companion
    depends_on:
      - proxy
    environment:
      NGINX_PROXY_CONTAINER: "proxy"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - proxy-certs:/etc/nginx/certs:rw
      - proxy-vhost:/etc/nginx/vhost.d
      - proxy-html:/usr/share/nginx/html
    healthcheck:
      test:
        - CMD-SHELL
        - pidof docker-gen >/dev/null 2>&1 && pidof letsencrypt_service >/dev/null 2>&1
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s

volumes:
  db-data:
  proxy-certs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./proxy/certs
  proxy-vhost:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./proxy/vhost.d
  proxy-html:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./proxy/html
  wp-db-data:
  wp-content:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./wp-content

networks:
  symfony-wp:
    internal: true
