**Decision (by Matthew):** Keep (active – valid and compliant)  
**Rationale:**  
GDPR-aligned Data Protection Consent API; valid spec v1.0, namespace update planned (v1.1).  
**Date:** 2025-10-20  **Status:** 🟢 Approved
