framework:
    cache:
        prefix_seed: silentoakranch/app
        app: cache.adapter.redis
        default_redis_provider: '%env(resolve:REDIS_URL)%'

when@test:
    framework:
        cache:
            app: cache.adapter.array
