global:
  smtp_smarthost: '${ALERTMANAGER_SMTP_HOST}:${ALERTMANAGER_SMTP_PORT}'
  smtp_from: '${ALERTMANAGER_SMTP_FROM}'
  smtp_auth_username: '${ALERTMANAGER_SMTP_USER}'
  smtp_auth_password: '${ALERTMANAGER_SMTP_PASSWORD}'
  smtp_require_tls: true

route:
  receiver: email
  group_by: ['alertname']
  group_interval: 5m
  repeat_interval: 2h
  routes:
    - receiver: telegram
      continue: false

receivers:
  - name: email
    email_configs:
      - to: '${ALERTMANAGER_EMAIL_TO}'
        send_resolved: true
        headers:
          Subject: '[SilentOak] {{ .CommonLabels.alertname }} on {{ .CommonLabels.instance }}'

  - name: telegram
    telegram_configs:
      - bot_token: '${ALERTMANAGER_TELEGRAM_TOKEN}'
        chat_id: '${ALERTMANAGER_TELEGRAM_CHAT_ID}'
        send_resolved: true
        message: '[SilentOak] {{ .CommonLabels.alertname }} on {{ .CommonLabels.instance }} ({{ .CommonAnnotations.summary }})'
