groups:
  - name: silent-oak-alerts
    rules:
      - alert: BackendHighErrorRate
        expr: increase(traefik_service_requests_total{service="backend@docker",code=~"5.."}[5m]) > 5
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Backend API error rate high"
          description: "More than 5 errors served by backend in the last 5 minutes."

      - alert: VolumeDiskUsageHigh
        expr: (node_filesystem_size_bytes{mountpoint="/"} - node_filesystem_avail_bytes{mountpoint="/"}) / node_filesystem_size_bytes{mountpoint="/"} > 0.8
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "Disk usage over 80%"
          description: "Check shared volumes and prune old backups."

      - alert: ContractQueueDelay
        expr: sor_queue_oldest_seconds > 60
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "Contract generation queue lagging"
          description: "Oldest message in messenger queue is {{ $value }} seconds old."
