name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install frontend dependencies
        working-directory: frontend
        run: npm ci

      - name: Lint frontend
        working-directory: frontend
        run: npm run lint

      - name: Test frontend modules with coverage
        working-directory: frontend
        run: npm test src/modules/invoices src/modules/agreements -- --coverage

      - name: Upload frontend coverage
        uses: actions/upload-artifact@v4
        with:
          name: frontend-coverage
          path: frontend/coverage

      - name: Build frontend
        working-directory: frontend
        run: npm run build

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2

      - name: Install backend dependencies
        working-directory: backend
        run: composer install --no-interaction --prefer-dist --ignore-platform-req=ext-sodium

      - name: Lint backend
        working-directory: backend
        run: find src -name '*.php' -print0 | xargs -0 -n1 php -l

      - name: Test backend with coverage
        working-directory: backend
        run: |
          mkdir -p coverage
          ./bin/phpunit --coverage-clover coverage/clover.xml \
            tests/InvoiceServiceTest.php \
            tests/AgreementServiceTest.php \
            tests/AgreementControllerSmokeTest.php

      - name: Upload backend coverage
        uses: actions/upload-artifact@v4
        with:
          name: backend-coverage
          path: backend/coverage
