name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Validate Composer configuration
        run: composer validate
        working-directory: backend

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install frontend dependencies
        run: npm ci
        working-directory: frontend

      - name: Run frontend tests
        run: npm test
        working-directory: frontend

      - name: Build backend image
        run: docker build --target builder -t backend-ci backend

      - name: Run PHPStan
        run: docker run --rm backend-ci vendor/bin/phpstan analyse

      - name: Run backend tests
        run: docker run --rm backend-ci vendor/bin/phpunit --testdox
