name: Deploy Silent Oak Ranch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.SOR_SERVER_HOST }}
          username: ${{ secrets.SOR_SERVER_USER }}
          key: ${{ secrets.SOR_SERVER_SSH_KEY }}
          script: |
            cd /srv/stallapp
            ./deploy.sh
