name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy application
    runs-on: ubuntu-latest
    needs: [build]
    env:
      SSH_USER: ${{ secrets.SSH_USER }}
      SSH_HOST: ${{ secrets.SSH_HOST }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Ensure target directory exists
        run: |
          ssh -o StrictHostKeyChecking=no "${SSH_USER}@${SSH_HOST}" "mkdir -p /srv/stallapp"

      - name: Sync repository
        run: |
          rsync -az --delete \
            --exclude='.git' \
            --exclude='node_modules' \
            --exclude='vendor' \
            --exclude='dist' \
            -e "ssh -o StrictHostKeyChecking=no" \
            ./ "${SSH_USER}@${SSH_HOST}:/srv/stallapp"

      - name: Update application services
        run: |
          ssh -o StrictHostKeyChecking=no "${SSH_USER}@${SSH_HOST}" <<'EOSSH'
          cd /srv/stallapp
          docker compose pull
          docker compose up -d --build
          docker system prune -f
          EOSSH
